---
##
# SSH config
#
- name: Install ssh server
  action: apt pkg=openssh-server state=installed

- name: ssh config
  action: template src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    - restart ssh
