- name: "Server setup tasks"
  hosts: all
  sudo: yes
  roles:
   - common
#   - Ansibles.nginx
   - varnish
   - php
#   - nodesource.nodejs
#   - joshualund.ruby-2_0_0

- name: Development Server
  hosts: development
  sudo: yes
  roles:
    - development

- name: Configure Site
  hosts: all
  sudo: yes
  roles:
    - site_config
